name: Build Flutter APK and AAB, Create Release

on:
  push:
    branches: [ master ]

jobs:
  build_and_release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Setup Flutter
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'  

      # Get Flutter dependencies
      - run: flutter pub get

      # Build APK and AAB
      - run: flutter build appbundle --release 
      - run: flutter build apk --release 

      # Create a release tag (e.g., 2023-08-21-14-35-20)
      - name: Create Release Tag
        id: create_tag
        run: |
          TAG=$(date +'%Y-%m-%d-%H-%M-%S')
          echo ::set-output name=TAG::$TAG
      # Create a GitHub release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }} # Required for release creation
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG }}
          release_name: Release ${{ steps.create_tag.outputs.TAG }} 
          draft: false
          prerelease: false

      # Upload APK and AAB as release assets
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: build/app/outputs/flutter-apk/app-release.apk
          asset_name: app-release.apk
          asset_content_type: application/vnd.android.package-archive

      - name: Upload Release Asset (AAB)
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: build/app/outputs/bundle/release/app-release.aab
          asset_name: app-release.aab
          asset_content_type: application/octet-stream 
